# 5 MOST Basic but MOST Important NumPy functions:

Write a short introduction about Numpy and list the chosen functions. (change this)

- random.uniform() function
- max, min and index of max and min using argmax/argmin function
- where() function 
- transpose function and cross product
- Mean, Mode and Median functions

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='zerotoanalyst-numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sarthak-s-1997/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations


'https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

## Function 1 - np.random.uniform()

This funciton helps us to generate random values within a defined range.


In [8]:
# Example 1

np.random.uniform(1,100)

98.9460692317283

Here, we generated a random value between 1 and 100.

In [11]:
# Example 2 

sample = np.random.uniform(1,100,10)

print(sample)

print(type(sample))

[ 3.95880341 83.6276737  20.32044381 90.75403564 52.04321613 30.24277068
 85.35729764 44.38827721 82.19434878 95.32721025]
<class 'numpy.ndarray'>


Here, we generated a numpy array containing random values which are under the defined range. We also defined exactly how many values we wanted in our array. 

In [14]:
# Example 3

sample = np.random.uniform(1,100,10).reshape(2,5)

print(sample)

np.random.uniform(1,100,10).reshape(6,3)

[[36.17582092 24.65654545 52.81100428 34.14306357 75.45070955]
 [31.40210798 31.51524225 21.23927624 48.24275729 34.75139364]]


ValueError: cannot reshape array of size 10 into shape (6,3)

Once we generate the random values we can also reshape them, however we have to be careful while reshaping them. For example since we generated 10 values it can be broken down into (2,5) but the same is not true for (6,3).

This function could be helpful while generating any data set for testing any AI/ML model.

In [16]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sarthak-s-1997/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations


'https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations'

## Max, Min and ARGMAX, ARGMIN 

Useful functions to find the min, max and the index of these values of a numpy array.

In [22]:
# Example 1

sample = np.random.randint(1,10,6)
print(sample)

print(np.max(sample))

print(np.min(sample))

[9 7 9 5 9 6]
9
5


Generated a sample numpy array, post then printed the maximun and minimum values present inside the same. 

In [24]:
# Example 2 

print(sample)

print(np.argmax(sample))
print(np.argmin(sample))

[9 7 9 5 9 6]
0
3


The argmax function provides us with the index of the numpy array where the value is maximum and minimum. 

In [31]:
# Example 3

sample1 = np.array([[10, 14, 12],
       [13, 11, 15]])

print(np.argmax(sample1, axis=0))
print(np.argmax(sample1, axis=1))


[1 0 1]
[1 2]


Here, we have used the argmax function to find the maximum value index along a particular axis of a 2D matrix. Note that these are indexes not the exact values.

We can also find the maximum value using the argmax function by calling something like array_name[argmax(array_name)]

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sarthak-s-1997/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations


'https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations'

## Where() function

This function helps us to identify a condition within a Numpy array and helps us to perform an action on the array when such condition is found.

Syntax of the where function:

np.where(condition,action if condition is true, action if condition is false)

In [34]:
# Example 

sample2=np.arange(1,100,10)
print(sample2)

np.where(sample2%3==0,0,1)

[ 1 11 21 31 41 51 61 71 81 91]


array([1, 1, 0, 1, 1, 0, 1, 1, 0, 1])

Here, we generated a random array, post that by using the where condition we replaced the elements which are divisible by 3 to 0 and rest all to 1. 

In [35]:
# Example 2

sample2=np.arange(1,100,10)
print(sample2)

np.where(sample2%3==0,0,sample2)

[ 1 11 21 31 41 51 61 71 81 91]


array([ 1, 11,  0, 31, 41,  0, 61, 71,  0, 91])

Similar to the where function in the above example, herein we have replaced the number divisible by 3 to 0 but have not changed any other elements of the array. 

In [38]:
# Example 3 - breaking


sample2=np.arange(1,100,14)
print(sample2)

print(sample2<50)

[ 1 15 29 43 57 71 85 99]
[ True  True  True  True False False False False]


Here, do not use the where function, however if we need to present a condition in a true and false manner we can easily do it by just print the required condition. 

Where function can be used to manipulate data effectively in any data set. 

In [39]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sarthak-s-1997/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations


'https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations'

## Transpose function and cross product.

Speaking in lay man's terms the transpose funtion is used to convert rows in columns and columns into rows. 

In [56]:
# Example 1 

a1=np.array([[2,3],[4,6]])

a2 = np.transpose(a1)

print(a2)

[[2 4]
 [3 6]]


Example of findind a 2x2 matrix. 

In [68]:
# Example 2 

a1=np.array([[2,3,7],[4,6,9],[4,8,2]])

a2 = np.transpose(a1)

print(a2)


[[2 4 4]
 [3 6 8]
 [7 9 2]]


Example of converting 3x3 matrix using transpose function. 

In [80]:
# Example 3 Verifying results:

c=np.eye(3)
print(c)

np.cross((np.transpose(c)),c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

As in mathematics, the cross product of two identity matrix is zero. The same is evident from the above example.

This function is useful while performing mathematical calculations. 

In [82]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sarthak-s-1997/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations


'https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations'

## Mean, Mode and Median functions

These are the most common tools used statistics.

In [89]:
# Example 1: Mean

b1 = np.array([99,86,87,88,86,103,87,94,78,77,85,86])

result = np.mean(b1)
print("The mean is: {}".format(result))

The mean is:88.0


Mean is the average value, which is sum of all the values divided by the number of values. 

In [92]:
# Example 2: Mode

b1 = np.array([99,86,87,88,86,103,87,94,78,77,85,86])

result = np.mode(b1)

print(b1)

AttributeError: module 'numpy' has no attribute 'mode'

There is no function for mode in numpy. We need to use an alternative such as "stats" from Scipy library to calculate the mode.

Mode is the most common value which in the above example is 86, which has shown up three times. 

In [93]:
# Example 3: Median

b1 = np.array([99,86,87,88,86,103,87,94,78,77,85,86])

result = np.median(b1)
print("The median is: {}".format(result))

The median is: 86.5


Median is the mid point value, if the total count of elements is even, then we take two numbers in the middle and calculate their average. 

These functions are useful in prediction of average, the middle, or the most common value inside the data set. 

-Sarthak Srivastava

In [94]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "sarthak-s-1997/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations


'https://jovian.ai/sarthak-s-1997/zerotoanalyst-numpy-array-operations'

## Conclusion

I have discussed the use case of a few common and useful numpy functions. However, the numpy library is huge and there is still a lot to explore. 

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Machine Learning Tutorial site: https://machinelearningknowledge.ai
* Youtube: https://www.youtube.com
* Useful Blog: https://levelup.gitconnected.com/50-numpy-functions-you-really-needed-for-data-science-fa09e8eb0cf0

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>